# ===========================================
# Fly's v1.1.1
# Made with <3 by Dötchen
# My first Public Project :D
# ===========================================

# !Make sure you don't forget any characters (Like ", : or ,)! Otherwise, the config will break! (config and messages)

# Message settings
messages:
  prefix: "&8[&b&lFlys&8] "

# Language settings (en = English, de = German, es = Spanish, fr = French, ru = Russian, pl = Polish)
language:
  language: "en"

# Permissions (customizable)
permissions:
  fly: "flys.fly"
  fly-others: "flys.fly.others"
  flyspeed: "flys.flyspeed"
  flyspeed-others: "flys.flyspeed.others"
  flyreload: "flys.flyreload"

# General settings
general:
  enable-particles: true
  enable-sounds: true
  flight-speed:
    default-speed: 0.1
    max-speed: 1.0

# World settings
worlds:
  # List of worlds where flying is allowed (empty = all worlds)
  # Example: ["world", "world_nether", "creative"]
  allowed-worlds: []
  # List of worlds where flying is disabled
  # Example: ["pvp_world", "hardcore", "minigames"]
  disabled-worlds: []
